<?php

return [
    'permissions' => [
        'dashboard.view' => ['name' => 'مشاهده داشبورد', 'group' => 'dashboard'],
        'storefront.manage' => ['name' => 'مدیریت صفحه اصلی فروشگاه', 'group' => 'storefront'],
        'catalog.manage' => ['name' => 'مدیریت کاتالوگ و محصولات', 'group' => 'catalog'],
        'inventory.manage' => ['name' => 'مدیریت موجودی', 'group' => 'catalog'],
        'orders.manage' => ['name' => 'مدیریت سفارش‌ها', 'group' => 'commerce'],
        'payments.manage' => ['name' => 'مدیریت پرداخت‌ها', 'group' => 'commerce'],
        'trades.manage' => ['name' => 'مدیریت معاوضه‌ها', 'group' => 'commerce'],
        'coupons.manage' => ['name' => 'مدیریت کدهای تخفیف', 'group' => 'commerce'],
        'content.manage' => ['name' => 'مدیریت محتوا و رسانه', 'group' => 'content'],
        'moderation.manage' => ['name' => 'مدیریت نظارت و گزارش محتوا', 'group' => 'content'],
        'reviews.manage' => ['name' => 'مدیریت دیدگاه‌ها و نقدها', 'group' => 'content'],
        'support.manage' => ['name' => 'مدیریت پشتیبانی و تیکت‌ها', 'group' => 'support'],
        'users.manage' => ['name' => 'مدیریت کاربران و دسترسی‌ها', 'group' => 'users'],
        'users.impersonate' => ['name' => 'ورود موقت به‌جای کاربر', 'group' => 'users'],
        'settings.manage' => ['name' => 'مدیریت تنظیمات فروشگاه', 'group' => 'system'],
        'sms.manage' => ['name' => 'مدیریت پیامک', 'group' => 'system'],
        'notifications.manage' => ['name' => 'مدیریت اعلان‌ها', 'group' => 'system'],
        'reports.view' => ['name' => 'مشاهده گزارش‌ها', 'group' => 'system'],
        'audit.view' => ['name' => 'مشاهده لاگ‌های مدیریتی', 'group' => 'system'],
        'system.maintenance' => ['name' => 'اجرای عملیات نگهداری سیستم', 'group' => 'system'],
        'system.deployments' => ['name' => 'مدیریت استقرار و به‌روزرسانی سیستم', 'group' => 'system'],
        'system.files.manage' => ['name' => 'مدیریت کامل فایل‌های پروژه', 'group' => 'system'],
    ],

    'permission_aliases' => [
        'users.manage' => ['user.manage'],
        'catalog.manage' => ['product.view', 'product.create', 'product.update', 'product.delete'],
        'orders.manage' => ['order.manage', 'order.view'],
        'payments.manage' => ['payment.manage'],
        'trades.manage' => ['trade.review'],
        'content.manage' => ['content.moderate'],
        'support.manage' => ['support.manage'],
        'settings.manage' => ['settings.manage'],
    ],

    'roles' => [
        'user' => [
            'name' => 'کاربر عادی',
            'description' => 'بدون دسترسی به پنل مدیریت',
            'permissions' => [],
        ],
        'super-admin' => [
            'name' => 'مدیر کل',
            'description' => 'دسترسی کامل و بدون محدودیت به تمام بخش‌های مدیریتی',
            'permissions' => '*',
        ],
        'admin' => [
            'name' => 'مدیر',
            'description' => 'مدیریت اجرایی سایت بدون دسترسی‌های زیرساختی و امنیتی مدیر کل',
            'permissions' => [
                'dashboard.view',
                'storefront.manage',
                'catalog.manage',
                'inventory.manage',
                'orders.manage',
                'payments.manage',
                'trades.manage',
                'coupons.manage',
                'content.manage',
                'moderation.manage',
                'reviews.manage',
                'support.manage',
                'settings.manage',
                'sms.manage',
                'notifications.manage',
                'reports.view',
            ],
        ],
        'product-manager' => [
            'name' => 'مدیر محصول',
            'description' => 'مدیریت محصولات، کاتالوگ و موجودی',
            'permissions' => [
                'dashboard.view',
                'storefront.manage',
                'catalog.manage',
                'inventory.manage',
                'reviews.manage',
            ],
        ],
        'content-moderator' => [
            'name' => 'ناظر محتوا',
            'description' => 'مدیریت محتوا، دیدگاه‌ها و گزارش‌های محتوایی',
            'permissions' => [
                'dashboard.view',
                'content.manage',
                'moderation.manage',
                'reviews.manage',
            ],
        ],
        'support' => [
            'name' => 'پشتیبانی',
            'description' => 'مدیریت تیکت‌ها و مشاهده اطلاعات لازم سفارش',
            'permissions' => [
                'dashboard.view',
                'support.manage',
                'orders.manage',
                'trades.manage',
            ],
        ],
        'editor' => [
            'name' => 'ویرایشگر',
            'description' => 'ایجاد و ویرایش محتوای سایت',
            'permissions' => [
                'dashboard.view',
                'content.manage',
            ],
        ],
        'warehouse' => [
            'name' => 'انباردار',
            'description' => 'مدیریت موجودی و مشاهده کاتالوگ',
            'permissions' => [
                'dashboard.view',
                'inventory.manage',
                'catalog.manage',
            ],
        ],
        'finance' => [
            'name' => 'مالی',
            'description' => 'مدیریت مالی، سفارش‌ها، تخفیف‌ها و گزارش‌ها',
            'permissions' => [
                'dashboard.view',
                'orders.manage',
                'payments.manage',
                'coupons.manage',
                'reports.view',
            ],
        ],
    ],

    'route_permissions' => [
        'admin.users.impersonate' => 'users.impersonate',
        'admin.users.*' => 'users.manage',
        'admin.dashboard' => 'dashboard.view',
        'admin.home.*' => 'storefront.manage',
        'admin.orders.*' => 'orders.manage',
        'admin.tickets.*' => 'support.manage',
        'admin.coupons.*' => 'coupons.manage',
        'admin.settings.*' => 'settings.manage',
        'admin.sms-patterns.*' => 'sms.manage',
        'admin.sms-test.*' => 'sms.manage',
        'admin.system-maintenance.*' => 'system.maintenance',
        'admin.deployments.*' => 'system.deployments',
        'admin.product-types.*' => 'catalog.manage',
        'admin.attributes.*' => 'catalog.manage',
        'admin.products.media.*' => 'catalog.manage',
        'admin.products.exchange.*' => 'catalog.manage',
        'admin.catalog.*' => 'catalog.manage',
        'admin.feed.*' => 'content.manage',
        'admin.studios.*' => 'content.manage',
        'admin.videos.*' => 'content.manage',
        'admin.video-playlists.*' => 'content.manage',
        'admin.shorts.*' => 'content.manage',
        'admin.uploads.*' => 'content.manage',
    ],

    'resource_permissions' => [
        'creators' => 'content.manage',
        'inventory' => 'inventory.manage',
        'payments' => 'payments.manage',
        'reviews' => 'reviews.manage',
        'trades' => 'trades.manage',
        'posts' => 'content.manage',
        'videos' => 'content.manage',
        'shorts' => 'content.manage',
        'comments' => 'moderation.manage',
        'reports' => 'reports.view',
        'moderation' => 'moderation.manage',
        'notifications' => 'notifications.manage',
        'banners' => 'content.manage',
        'pages' => 'content.manage',
        'audit-logs' => 'audit.view',
        'support' => 'support.manage',
    ],
];
