import { Avatar, Button } from "@heroui/react";
import { Link } from "@inertiajs/react";
import { ExternalLink, Factory, Gamepad2, ListVideo, Play, Users } from "lucide-react";

import Pagination from "../../Components/Storefront/Shared/Pagination";
import Seo, { type SeoData } from "../../Components/Seo";
import StorefrontLayout from "../../Layouts/StorefrontLayout";
import type { Paginated } from "../../types";

interface Studio { id: number; name: string; slug: string; url: string; logo_url: string | null; background_url: string | null; description: string | null; description_html: string | null; website: string | null; channels_count: number }
interface Channel { id: number; name: string; slug: string; url: string; logo_url: string | null; background_url: string | null; videos_count: number; followers_count: number }
interface Collection { id: number; title: string; description: string | null; url: string; logo_url: string | null; channel_name: string; videos_count: number }
export default function StudioShow({ seo, studio, channels, collections }: { seo: SeoData; studio: Studio; channels: Paginated<Channel>; collections: Paginated<Collection> }) {
    return <StorefrontLayout><Seo seo={seo} /><main className="pb-14">
        <section className="relative h-52 overflow-hidden bg-slate-950 sm:h-72 lg:h-80">{studio.background_url ? <img alt={`پس‌زمینه ${studio.name}`} className="size-full object-cover" src={studio.background_url} /> : <span className="grid size-full place-items-center text-slate-700"><Factory size={72} /></span>}<span className="absolute inset-0 bg-gradient-to-t from-[var(--store-bg)] via-black/25 to-black/10" /></section>
        <div className="relative mx-auto -mt-20 max-w-7xl px-3 sm:px-5"><header className="flex flex-col items-start gap-4 rounded-3xl border border-[var(--store-border)] bg-[var(--store-panel)]/95 p-5 shadow-2xl backdrop-blur-xl sm:flex-row sm:items-center"><Avatar className="size-24 shrink-0 border-4 border-[var(--store-panel)] shadow-xl sm:size-32">{studio.logo_url && <Avatar.Image alt={`لوگوی ${studio.name}`} src={studio.logo_url} />}<Avatar.Fallback><Factory size={38} /></Avatar.Fallback></Avatar><div className="min-w-0 flex-1"><p className="text-xs font-black text-indigo-400">GAME STUDIO</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">{studio.name}</h1><p className="mt-2 text-sm text-[var(--store-muted)]">{studio.channels_count.toLocaleString("fa-IR")} کانال مرتبط</p></div>{studio.website && <a href={studio.website} rel="noreferrer" target="_blank"><Button variant="secondary"><ExternalLink size={17} /> وب‌سایت رسمی</Button></a>}</header>
            {studio.description_html && <section className="mx-auto mt-6 max-w-4xl rounded-3xl border border-[var(--store-border)] bg-[var(--store-panel)] p-5 sm:p-7"><h2 className="mb-4 text-xl font-black">درباره {studio.name}</h2><div className="store-rich-text" dangerouslySetInnerHTML={{ __html: studio.description_html }} /></section>}
            <section className="mt-9"><div className="mb-5 flex items-center gap-2"><Gamepad2 className="text-indigo-400" size={20} /><h2 className="text-xl font-black">کانال‌های {studio.name}</h2></div>{channels.data.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{channels.data.map((channel) => <Link className="group overflow-hidden rounded-3xl border border-[var(--store-border)] bg-[var(--store-panel)] transition hover:border-indigo-500/50" href={channel.url} key={channel.id}><div className="relative h-32 bg-slate-950">{channel.background_url && <img alt="" className="size-full object-cover opacity-75 transition group-hover:scale-105" loading="lazy" src={channel.background_url} />}<span className="absolute inset-0 bg-gradient-to-t from-black/90 to-transparent" /><Avatar className="absolute -bottom-6 right-4 size-16 border-4 border-[var(--store-panel)]">{channel.logo_url && <Avatar.Image alt={channel.name} src={channel.logo_url} />}<Avatar.Fallback><Gamepad2 /></Avatar.Fallback></Avatar></div><div className="px-4 pb-4 pt-9"><h3 className="font-black group-hover:text-indigo-400">{channel.name}</h3><div className="mt-3 flex gap-4 text-[11px] text-[var(--store-muted)]"><span className="flex items-center gap-1"><Users size={13} />{channel.followers_count.toLocaleString("fa-IR")}</span><span className="flex items-center gap-1"><Play size={13} />{channel.videos_count.toLocaleString("fa-IR")} ویدیو</span></div></div></Link>)}</div> : <div className="rounded-3xl border border-dashed border-[var(--store-border)] p-14 text-center text-[var(--store-muted)]">هنوز کانالی به این استودیو متصل نشده است.</div>}<Pagination links={channels.links} /></section>
            <section className="mt-10"><div className="mb-5 flex items-center gap-2"><ListVideo className="text-violet-400" size={20} /><h2 className="text-xl font-black">کالکشن‌های {studio.name}</h2></div>{collections.data.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{collections.data.map((collection) => <Link className="group overflow-hidden rounded-3xl border border-[var(--store-border)] bg-[var(--store-panel)] transition hover:-translate-y-1 hover:border-violet-500/50" href={collection.url} key={collection.id}><div className="aspect-video overflow-hidden bg-slate-950">{collection.logo_url ? <img alt={collection.title} className="size-full object-cover transition duration-300 group-hover:scale-105" loading="lazy" src={collection.logo_url} /> : <span className="grid size-full place-items-center text-slate-600"><ListVideo size={48} /></span>}</div><div className="p-4"><p className="text-xs font-bold text-violet-400">{collection.channel_name}</p><h3 className="mt-1 font-black group-hover:text-violet-400">{collection.title}</h3>{collection.description && <p className="mt-2 line-clamp-2 text-xs leading-6 text-[var(--store-muted)]">{collection.description}</p>}<span className="mt-3 flex items-center gap-1 text-xs text-[var(--store-muted)]"><Play size={13} />{collection.videos_count.toLocaleString("fa-IR")} ویدیو</span></div></Link>)}</div> : <div className="rounded-3xl border border-dashed border-[var(--store-border)] p-14 text-center text-[var(--store-muted)]">هنوز کالکشنی به این استودیو متصل نشده است.</div>}<Pagination links={collections.links} /></section>
        </div>
    </main></StorefrontLayout>;
}
