import { Button, Card, Chip, Input } from "@heroui/react";
import { Head, router, usePage } from "@inertiajs/react";
import { ChevronLeft, ChevronRight, KeyRound, LogIn, Search, ShieldCheck, UserCog, X } from "lucide-react";
import { type FormEvent, useState } from "react";
import AdminLayout from "../../../Layouts/AdminLayout";
import type { SharedPageProps } from "../../../types";

type User = { id:number;name:string;email:string|null;phone:string|null;username:string|null;status:string;role:string;is_admin:boolean;wallet_balance:number;email_verified:boolean;phone_verified:boolean;last_login_at:string|null;created_at:string;permission_ids:number[];orders_count:number };
type Role = { id:number;name:string;slug:string;permission_ids:number[] };
type Permission = { id:number;name:string;slug:string;group:string };
type Pagination = { data:User[];current_page:number;last_page:number;per_page:number;total:number;from:number|null;to:number|null };
type Props = { users:Pagination;roles:Role[];permissions:Record<string,Permission[]>;filters:{search:string;status:string;role:string;admin:string;per_page?:number} };
const fa = new Intl.NumberFormat("fa-IR");
const statusLabel:Record<string,string>={active:"فعال",inactive:"غیرفعال",blocked:"مسدود"};

export default function UsersIndex({users,roles,permissions,filters}:Props){
 const {auth}=usePage<SharedPageProps>().props;const[search,setSearch]=useState(filters.search);const[selected,setSelected]=useState<User|null>(null);
 const [form,setForm]=useState({status:"active",role:"user",is_admin:false,permissions:[] as number[]});
 const query=(next:Record<string,unknown>)=>router.get("/admin/users",{...filters,...next},{preserveState:true,replace:true});
 const open=(user:User)=>{setSelected(user);setForm({status:user.status,role:user.role,is_admin:user.is_admin,permissions:user.permission_ids})};
 const save=()=>selected&&router.patch(`/admin/users/${selected.id}`,form,{preserveScroll:true,onSuccess:()=>setSelected(null)});
 const roleChange=(slug:string)=>{const role=roles.find(item=>item.slug===slug);setForm(value=>({...value,role:slug,permissions:role?.permission_ids??value.permissions}))};
 return <AdminLayout title="مدیریت کاربران" description="کنترل حساب‌ها، نقش‌ها، دسترسی‌ها و ورود آزمایشی به‌جای کاربر"><Head title="مدیریت کاربران"/>
  <Card className="mb-5 border border-slate-800 bg-slate-900/60" variant="secondary"><Card.Content className="grid gap-3 p-4 md:grid-cols-[minmax(240px,1fr)_repeat(4,minmax(130px,auto))]">
   <form className="flex gap-2" onSubmit={(e:FormEvent)=>{e.preventDefault();query({search,page:1})}}><Input aria-label="جستجوی کاربران" placeholder="نام، ایمیل، موبایل یا نام کاربری" value={search} onChange={e=>setSearch(e.target.value)}/><Button isIconOnly type="submit" variant="primary"><Search size={17}/></Button></form>
   <select className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" value={filters.status} onChange={e=>query({status:e.target.value,page:1})}><option value="">همه وضعیت‌ها</option><option value="active">فعال</option><option value="inactive">غیرفعال</option><option value="blocked">مسدود</option></select>
   <select className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" value={filters.role} onChange={e=>query({role:e.target.value,page:1})}><option value="">همه نقش‌ها</option>{roles.map(role=><option key={role.id} value={role.slug}>{role.name}</option>)}</select>
   <select className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" value={filters.admin} onChange={e=>query({admin:e.target.value,page:1})}><option value="">همه دسترسی‌ها</option><option value="1">مدیران</option><option value="0">کاربران عادی</option></select>
   <select className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" value={users.per_page} onChange={e=>query({per_page:Number(e.target.value),page:1})}><option value="12">۱۲ در صفحه</option><option value="24">۲۴ در صفحه</option><option value="48">۴۸ در صفحه</option></select>
  </Card.Content></Card>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{users.data.map(user=><Card className="border border-slate-800 bg-slate-900/65 transition hover:-translate-y-0.5 hover:border-indigo-500/30" key={user.id} variant="secondary"><Card.Content className="p-5">
   <div className="flex items-start gap-3"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-700 text-lg font-black">{user.name.slice(0,1)}</div><div className="min-w-0 flex-1"><p className="truncate font-bold text-white">{user.name}</p><p className="truncate text-xs text-slate-500" dir="ltr">{user.email??user.phone??"بدون راه ارتباطی"}</p></div><Chip size="sm" variant="soft">{statusLabel[user.status]??user.status}</Chip></div>
   <div className="mt-4 grid grid-cols-3 gap-2 text-center"><Stat label="سفارش" value={fa.format(user.orders_count)}/><Stat label="کیف پول" value={fa.format(user.wallet_balance)}/><Stat label="شناسه" value={`#${fa.format(user.id)}`}/></div>
   <div className="mt-4 flex flex-wrap gap-2"><Chip size="sm">{roles.find(r=>r.slug===user.role)?.name??user.role}</Chip>{user.is_admin&&<Chip color="accent" size="sm"><ShieldCheck size={12}/> پنل مدیریت</Chip>}{(user.email_verified||user.phone_verified)&&<Chip size="sm" variant="soft">تأییدشده</Chip>}</div>
   <p className="mt-4 text-[11px] text-slate-600">عضویت: {new Date(user.created_at).toLocaleDateString("fa-IR")}{user.last_login_at&&` · آخرین ورود: ${new Date(user.last_login_at).toLocaleDateString("fa-IR")}`}</p>
   <div className="mt-4 grid grid-cols-2 gap-2"><Button onPress={()=>open(user)} size="sm" variant="secondary"><UserCog size={15}/>مدیریت</Button><Button isDisabled={auth.user?.id===user.id} onPress={()=>{if(confirm(`ورود به‌عنوان ${user.name}؟`))router.post(`/admin/users/${user.id}/impersonate`)}} size="sm" variant="ghost"><LogIn size={15}/>ورود با کاربر</Button></div>
  </Card.Content></Card>)}</div>
  {users.data.length===0&&<div className="rounded-3xl border border-dashed border-slate-700 py-20 text-center text-slate-500">کاربری با این فیلترها پیدا نشد.</div>}
  <div className="mt-6 flex flex-col items-center justify-between gap-3 rounded-2xl border border-slate-800 bg-slate-900/50 p-4 sm:flex-row"><p className="text-xs text-slate-500">نمایش {fa.format(users.from??0)} تا {fa.format(users.to??0)} از {fa.format(users.total)} کاربر</p><div className="flex items-center gap-2"><Button isDisabled={users.current_page===1} isIconOnly onPress={()=>query({page:users.current_page-1})} size="sm" variant="ghost"><ChevronRight/></Button><span className="text-xs">صفحه {fa.format(users.current_page)} از {fa.format(users.last_page)}</span><Button isDisabled={users.current_page===users.last_page} isIconOnly onPress={()=>query({page:users.current_page+1})} size="sm" variant="ghost"><ChevronLeft/></Button></div></div>
  {selected&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/75 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-slate-700 bg-[#0b0f18] shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b border-slate-800 bg-[#0b0f18]/95 p-5"><div><h2 className="font-black">مدیریت {selected.name}</h2><p className="text-xs text-slate-500">نقش، وضعیت و دسترسی‌های مستقیم</p></div><Button isIconOnly onPress={()=>setSelected(null)} variant="ghost"><X/></Button></div><div className="space-y-6 p-5">
   <div className="grid gap-4 sm:grid-cols-3"><label className="space-y-2 text-xs font-bold">وضعیت<select className="h-11 w-full rounded-xl border border-slate-700 bg-slate-950 px-3" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">فعال</option><option value="inactive">غیرفعال</option><option value="blocked">مسدود</option></select></label><label className="space-y-2 text-xs font-bold">نقش<select className="h-11 w-full rounded-xl border border-slate-700 bg-slate-950 px-3" value={form.role} onChange={e=>roleChange(e.target.value)}>{roles.map(role=><option key={role.id} value={role.slug}>{role.name}</option>)}</select></label><label className="flex items-center gap-3 rounded-xl border border-slate-700 bg-slate-950 px-4 text-xs font-bold"><input checked={form.is_admin} className="size-4 accent-indigo-500" disabled={auth.user?.id===selected.id} onChange={e=>setForm({...form,is_admin:e.target.checked})} type="checkbox"/>دسترسی ورود به پنل</label></div>
   <div><h3 className="mb-3 flex items-center gap-2 text-sm font-bold"><KeyRound size={16}/>دسترسی‌های مستقیم</h3><div className="space-y-4">{Object.entries(permissions).map(([group,items])=><section className="rounded-2xl border border-slate-800 p-4" key={group}><p className="mb-3 text-xs font-bold text-indigo-400">{group}</p><div className="grid gap-2 sm:grid-cols-2">{items.map(permission=><label className="flex items-center gap-2 text-xs text-slate-300" key={permission.id}><input checked={form.permissions.includes(permission.id)} className="accent-indigo-500" onChange={e=>setForm(value=>({...value,permissions:e.target.checked?[...value.permissions,permission.id]:value.permissions.filter(id=>id!==permission.id)}))} type="checkbox"/>{permission.name}<span className="text-[10px] text-slate-600">{permission.slug}</span></label>)}</div></section>)}</div></div>
   <Button className="w-full" onPress={save} variant="primary">ذخیره تغییرات</Button>
  </div></div></div>}
 </AdminLayout>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-950/60 p-2"><strong className="block text-xs text-slate-200">{value}</strong><span className="text-[10px] text-slate-600">{label}</span></div>}
